
services:

  mongo:
    image: mongo:latest
    container_name: my-mongo
    environment:
      MONGO_INITDB_DATABASE: users-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init-scripts/:/docker-entrypoint-initdb.d/
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
    mongo-data:
