
services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/src/shared
    environment:
      - PORT=8080
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo:latest
    container_name: ZoopMongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
